
eureka:
   client:
     register-with-eureka: true
     fetch-registry: true
     service-url:
       defaultZone: http://registryProject:8761/eureka/
   instance:
     prefer-ip-address: true
     hostname: registryProject
     non-secure-port: 8085
