
eureka:
   client:
     register-with-eureka: true
     fetch-registry: true
     service-url:
       defaultZone: http://172.19.0.2/16:8761/eureka/
   instance:
     prefer-ip-address: true
     hostname: 172.19.0.2/16
     non-secure-port: 8085
